# Generated by Django 3.2.5 on 2021-11-24 06:23

import django.contrib.postgres.indexes
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='operation id')),
                ('name', models.CharField(max_length=255, null=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('type_id', models.UUIDField(null=True)),
                ('type_name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('operation_ip', models.GenericIPAddressField(null=True)),
                ('operation_address', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
            ],
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='operation_l_created_fa135c_brin'),
        ),
    ]
