# Generated by Django 3.2.5 on 2021-11-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='type_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
