# Generated by Django 3.2.5 on 2021-11-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_log', '0002_alter_operationlog_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='type_id',
            field=models.UUIDField(null=True),
        ),
    ]
